version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: expensetracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expense-tracker-network

  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - expense-tracker-network

volumes:
  postgres_data:

networks:
  expense-tracker-network:
    driver: bridge
